services:
  kafka:
    url:
      - "localhost:29092"
      - "localhost:29093"
  auth:
    grpcPort: "localhost:9090"
    httpPort: "localhost:8081"
    database:
      host: "localhost"
      port: "5432"
      username: "myuser"
      password: "mypassword"
      database: "authdb"
  users:
    grpcPort: "localhost:9091"
    httpPort: "localhost:8082"
    database:
      host: "localhost"
      port: "5434"
      username: "myuser"
      password: "mypassword"
      database: "usersdb"
  api-gateway:
    addr: "localhost:3000"
  match:
    grpcPort: "localhost9092"
    httpPort: "localhost:8083"
    database:
      host: "localhost"
      port: "5436"
      username: "myuser"
      password: "mypassword"
      database: "matchdb"
  deck:
    grpcPort: "localhost9093"
    httpPort: "localhost:8084"
  object-storage:
    bucket: tinder-clone-danilkompaniets.s3.ru-7.storage.selcloud.ru
    region: ru-7
    endpoint: s3.ru-7.storage.selcloud.ru
    useSSl: false
    